cob-shutdown wait until pcs are down

diff --git a/scripts/cob-shutdown b/scripts/cob-shutdown
--- a/scripts/cob-shutdown
+++ b/scripts/cob-shutdown
@@ -8,7 +8,6 @@ if [ "$HOSTNAME" != "$robot_name-b1" ]; then
 	exit
 fi
 
-
 client_list="
 $robot_name-t1
 $robot_name-t2
@@ -24,16 +23,26 @@ $robot_name-b1"
 #done
 
 for client in $client_list; do
-	echo "-------------------------------------------"
-	echo "Executing <<"shutdown">> on $client"
-	echo "-------------------------------------------"
-	echo ""
-	ssh $client "sudo shutdown now -P 0"
-	ret=${PIPESTATUS[0]}
-	if [ $ret != 0 ] ; then
-		echo "command return an error (error code: $ret), aborting..."
-		#exit 1
-	fi
-	echo ""
+    echo "-------------------------------------------"
+    echo "Executing <<"shutdown">> on $client"  
+    echo "-------------------------------------------"
+    echo ""
+    ssh $client "sudo shutdown now -P 0"
+    if [ $ret != 0 ] ; then
+      echo "command return an error (error code: $ret), aborting..."
+    fi
+    ret=${PIPESTATUS[0]}
+    shutdown=false
+    while ! ($shutdown); do
+      ping -c 1 -w 3 $client
+      if [ $? -ne 0 ] ; then
+        shutdown=true
+        echo $client down
+        break
+      else
+        echo "waiting for" $client
+      fi
+      sleep 1
+    done
+    echo "done"
 done
-
